import {
  Company,
  Contact,
  Lead,
  Deal,
  Project,
  Task,
  Employee,
  Department,
  AttendanceRecord,
  LeaveRequest,
  Candidate,
  JobPosition,
  Expense,
  Asset,
  DocumentItem,
  NoteItem,
  ActivityItem,
  AuditLogItem,
  AutomationRule,
  SystemSettings,
  User,
  Milestone,
  UserInvitation,
} from "../types";

export const initialUsers: User[] = [
  {
    id: "usr-01",
    name: "Alex Vance",
    email: "alex.vance@worqester.internal",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    role: "Admin",
    department: "Executive Management",
    jobTitle: "Chief Operations Officer",
    organizationId: "org-worqester-01",
  },
  {
    id: "usr-02",
    name: "Priya Sharma",
    email: "priya.sharma@worqester.internal",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    role: "HR Manager",
    department: "Human Resources",
    jobTitle: "Head of People & Culture",
    organizationId: "org-worqester-01",
  },
  {
    id: "usr-03",
    name: "Marcus Reed",
    email: "marcus.reed@worqester.internal",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    role: "Sales Manager",
    department: "Sales & Revenue",
    jobTitle: "Director of Enterprise Sales",
    organizationId: "org-worqester-01",
  },
  {
    id: "usr-04",
    name: "Elena Rostova",
    email: "elena.rostova@worqester.internal",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    role: "Project Manager",
    department: "Engineering",
    jobTitle: "Principal Technical Program Manager",
    organizationId: "org-worqester-01",
  },
  {
    id: "usr-05",
    name: "Vikram Patel",
    email: "vikram.patel@worqester.internal",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    role: "Employee",
    department: "Engineering",
    jobTitle: "Lead Full Stack Engineer",
    organizationId: "org-worqester-01",
  },
];

export const initialSettings: SystemSettings = {
  companyName: "Worqester Technologies",
  tagline: "Manage Customers. People. Projects. Growth.",
  currency: "INR",
  currencySymbol: "₹",
  timezone: "Asia/Kolkata (IST, UTC+5:30)",
  theme: "dark",
  enabledModules: {
    crm: true,
    projects: true,
    tasks: true,
    hrm: true,
    recruitment: true,
    attendance: true,
    expenses: true,
    assets: true,
    documents: true,
    reports: true,
    ai: true,
    automations: true,
  },
  modulesEnabled: {
    crm: true,
    projects: true,
    tasks: true,
    hrm: true,
    recruitment: true,
    attendance: true,
    expenses: true,
    assets: true,
    documents: true,
    reports: true,
    ai: true,
    automations: true,
  },
};

export const initialCompanies: Company[] = [
  {
    id: "comp-01",
    organizationId: "org-worqester-01",
    name: "Acme Technologies",
    industry: "Cloud & AI Infrastructure",
    website: "https://acme-technologies.demo",
    phone: "+91 98765 43210",
    email: "partnerships@acme-technologies.demo",
    address: "Tech Park Phase 2, Bengaluru, KA",
    employeesCount: 450,
    annualRevenue: 28500000,
    ownerId: "usr-03",
    ownerName: "Marcus Reed",
    health: "Healthy",
    healthReason: "High NPS feedback, active project deliverables, expansion contract in pipeline.",
    tags: ["Tier 1", "Strategic", "Cloud Migrations"],
    createdAt: "2026-01-15",
    updatedAt: "2026-08-20",
  },
  {
    id: "comp-02",
    organizationId: "org-worqester-01",
    name: "Nova Systems",
    industry: "Financial Software",
    website: "https://novasystems.demo",
    phone: "+91 98220 11223",
    email: "enterprise@novasystems.demo",
    address: "Bandra Kurla Complex, Mumbai, MH",
    employeesCount: 320,
    annualRevenue: 19800000,
    ownerId: "usr-03",
    ownerName: "Marcus Reed",
    health: "At Risk",
    healthReason: "Pending renewal approval; open blocker task in auth security migration.",
    tags: ["BFSI", "High Touch"],
    createdAt: "2026-02-10",
    updatedAt: "2026-08-28",
  },
  {
    id: "comp-03",
    organizationId: "org-worqester-01",
    name: "Vertex Solutions",
    industry: "Industrial IoT",
    website: "https://vertex-iot.demo",
    phone: "+91 91234 56789",
    email: "contact@vertex-iot.demo",
    address: "Cyber City, Gurugram, HR",
    employeesCount: 180,
    annualRevenue: 14200000,
    ownerId: "usr-03",
    ownerName: "Marcus Reed",
    health: "Watch",
    healthReason: "Leadership restructuring at client side; communication velocity slowed.",
    tags: ["IoT", "Manufacturing"],
    createdAt: "2026-02-28",
    updatedAt: "2026-08-30",
  },
  {
    id: "comp-04",
    organizationId: "org-worqester-01",
    name: "BlueWave Digital",
    industry: "E-Commerce Logistics",
    website: "https://bluewave-logistics.demo",
    phone: "+91 97112 33445",
    email: "procure@bluewave.demo",
    address: "Hitec City, Hyderabad, TS",
    employeesCount: 520,
    annualRevenue: 34000000,
    ownerId: "usr-03",
    ownerName: "Marcus Reed",
    health: "Healthy",
    healthReason: "Successfully onboarded warehouse microservice stack; on-time milestones.",
    tags: ["Logistics", "Retail"],
    createdAt: "2026-03-05",
    updatedAt: "2026-09-01",
  },
  {
    id: "comp-05",
    organizationId: "org-worqester-01",
    name: "Orion Enterprises",
    industry: "Healthcare Systems",
    website: "https://orion-health.demo",
    phone: "+91 96543 21098",
    email: "ops@orion-health.demo",
    address: "Tidel Park, Chennai, TN",
    employeesCount: 290,
    annualRevenue: 22000000,
    ownerId: "usr-01",
    ownerName: "Alex Vance",
    health: "Watch",
    healthReason: "HIPAA compliance audit in progress; 2 milestone reviews pending.",
    tags: ["Healthcare", "Strict SLA"],
    createdAt: "2026-03-22",
    updatedAt: "2026-08-25",
  },
  {
    id: "comp-06",
    organizationId: "org-worqester-01",
    name: "Zenith Global Telecom",
    industry: "Telecommunications",
    website: "https://zenithtelecom.demo",
    phone: "+91 95432 10987",
    email: "enterprise@zenithtelecom.demo",
    address: "Viman Nagar, Pune, MH",
    employeesCount: 850,
    annualRevenue: 64000000,
    ownerId: "usr-03",
    ownerName: "Marcus Reed",
    health: "Healthy",
    healthReason: "Multi-year managed services contract active with steady consumption.",
    tags: ["Telecom", "Enterprise Plus"],
    createdAt: "2026-04-12",
    updatedAt: "2026-09-02",
  },
  {
    id: "comp-07",
    organizationId: "org-worqester-01",
    name: "Apex Logistics Hub",
    industry: "Supply Chain Solutions",
    website: "https://apexlogistics.demo",
    phone: "+91 94321 09876",
    email: "info@apexlogistics.demo",
    address: "Sector 62, Noida, UP",
    employeesCount: 140,
    annualRevenue: 9800000,
    ownerId: "usr-03",
    ownerName: "Marcus Reed",
    health: "Critical",
    healthReason: "Payment overdue by 35 days; key champion resigned.",
    tags: ["High Risk", "Credit Hold"],
    createdAt: "2026-04-18",
    updatedAt: "2026-08-15",
  },
  {
    id: "comp-08",
    organizationId: "org-worqester-01",
    name: "Radiant BioTech",
    industry: "Life Sciences & Pharma",
    website: "https://radiantbio.demo",
    phone: "+91 93210 98765",
    email: "admin@radiantbio.demo",
    address: "Genome Valley, Hyderabad, TS",
    employeesCount: 210,
    annualRevenue: 17500000,
    ownerId: "usr-01",
    ownerName: "Alex Vance",
    health: "Healthy",
    healthReason: "New drug discovery data workflow project launched smoothly.",
    tags: ["BioTech", "R&D"],
    createdAt: "2026-05-02",
    updatedAt: "2026-08-30",
  },
  {
    id: "comp-09",
    organizationId: "org-worqester-01",
    name: "Stellar Commerce Inc",
    industry: "D2C Brands Hub",
    website: "https://stellarcommerce.demo",
    phone: "+91 92109 87654",
    email: "growth@stellarcommerce.demo",
    address: "Indiranagar, Bengaluru, KA",
    employeesCount: 95,
    annualRevenue: 8200000,
    ownerId: "usr-03",
    ownerName: "Marcus Reed",
    health: "Healthy",
    healthReason: "Rapid GMV scale; request for AI personalization integration.",
    tags: ["Fast Growth", "E-Commerce"],
    createdAt: "2026-05-20",
    updatedAt: "2026-09-03",
  },
  {
    id: "comp-10",
    organizationId: "org-worqester-01",
    name: "Quantum FinTech Labs",
    industry: "Decentralized Finance & NeoBanking",
    website: "https://quantumfin.demo",
    phone: "+91 91098 76543",
    email: "partners@quantumfin.demo",
    address: "FinTech City, GIFT City, GJ",
    employeesCount: 160,
    annualRevenue: 16800000,
    ownerId: "usr-03",
    ownerName: "Marcus Reed",
    health: "Healthy",
    healthReason: "Regulatory sandbox cleared; full enterprise licensing initiated.",
    tags: ["FinTech", "API-first"],
    createdAt: "2026-06-11",
    updatedAt: "2026-09-02",
  },
];

export const initialContacts: Contact[] = [
  {
    id: "cont-01",
    organizationId: "org-worqester-01",
    companyId: "comp-01",
    companyName: "Acme Technologies",
    name: "Rajesh Kulkarni",
    designation: "Chief Technology Officer",
    email: "rajesh.k@acme-technologies.demo",
    phone: "+91 98765 00001",
    location: "Bengaluru",
    lastContacted: "2026-08-28",
    nextFollowUp: "2026-09-08",
    tags: ["Decision Maker", "Technical"],
    createdAt: "2026-01-20",
  },
  {
    id: "cont-02",
    organizationId: "org-worqester-01",
    companyId: "comp-01",
    companyName: "Acme Technologies",
    name: "Anita Deshmukh",
    designation: "VP Engineering",
    email: "anita.d@acme-technologies.demo",
    phone: "+91 98765 00002",
    location: "Bengaluru",
    lastContacted: "2026-08-25",
    tags: ["Sponsor"],
    createdAt: "2026-01-22",
  },
  {
    id: "cont-03",
    organizationId: "org-worqester-01",
    companyId: "comp-02",
    companyName: "Nova Systems",
    name: "Siddharth Sen",
    designation: "Head of Infrastructure",
    email: "siddharth.s@novasystems.demo",
    phone: "+91 98220 00001",
    location: "Mumbai",
    lastContacted: "2026-08-18",
    nextFollowUp: "2026-09-05",
    tags: ["Champion"],
    createdAt: "2026-02-12",
  },
  {
    id: "cont-04",
    organizationId: "org-worqester-01",
    companyId: "comp-03",
    companyName: "Vertex Solutions",
    name: "Meera Krishnan",
    designation: "Director of Supply Chain IT",
    email: "meera.k@vertex-iot.demo",
    phone: "+91 91234 00001",
    location: "Gurugram",
    lastContacted: "2026-08-29",
    nextFollowUp: "2026-09-10",
    tags: ["Buyer"],
    createdAt: "2026-03-01",
  },
  {
    id: "cont-05",
    organizationId: "org-worqester-01",
    companyId: "comp-04",
    companyName: "BlueWave Digital",
    name: "Karan Johar-Roy",
    designation: "Chief Operating Officer",
    email: "karan.roy@bluewave.demo",
    phone: "+91 97112 00001",
    location: "Hyderabad",
    lastContacted: "2026-09-01",
    tags: ["Executive"],
    createdAt: "2026-03-10",
  },
  {
    id: "cont-06",
    organizationId: "org-worqester-01",
    companyId: "comp-05",
    companyName: "Orion Enterprises",
    name: "Dr. Lakshmi Narayanan",
    designation: "Chief Medical Information Officer",
    email: "lakshmi.n@orion-health.demo",
    phone: "+91 96543 00001",
    location: "Chennai",
    lastContacted: "2026-08-20",
    nextFollowUp: "2026-09-07",
    tags: ["Compliance", "Healthcare"],
    createdAt: "2026-03-25",
  },
  {
    id: "cont-07",
    organizationId: "org-worqester-01",
    companyId: "comp-06",
    companyName: "Zenith Global Telecom",
    name: "Arjun Singhal",
    designation: "VP Enterprise Architecture",
    email: "arjun.s@zenithtelecom.demo",
    phone: "+91 95432 00001",
    location: "Pune",
    lastContacted: "2026-08-31",
    tags: ["Architect"],
    createdAt: "2026-04-15",
  },
  {
    id: "cont-08",
    organizationId: "org-worqester-01",
    companyId: "comp-07",
    companyName: "Apex Logistics Hub",
    name: "Vikas Aggarwal",
    designation: "General Manager IT",
    email: "vikas.a@apexlogistics.demo",
    phone: "+91 94321 00001",
    location: "Noida",
    lastContacted: "2026-08-10",
    tags: ["At Risk Contact"],
    createdAt: "2026-04-20",
  },
  {
    id: "cont-09",
    organizationId: "org-worqester-01",
    companyId: "comp-08",
    companyName: "Radiant BioTech",
    name: "Dr. Sunita Rao",
    designation: "Head of Computational Genomics",
    email: "sunita.rao@radiantbio.demo",
    phone: "+91 93210 00001",
    location: "Hyderabad",
    lastContacted: "2026-08-26",
    tags: ["Research"],
    createdAt: "2026-05-05",
  },
  {
    id: "cont-10",
    organizationId: "org-worqester-01",
    companyId: "comp-09",
    companyName: "Stellar Commerce Inc",
    name: "Tanmay Bhatia",
    designation: "Co-Founder & VP Product",
    email: "tanmay@stellarcommerce.demo",
    phone: "+91 92109 00001",
    location: "Bengaluru",
    lastContacted: "2026-09-02",
    tags: ["Founder"],
    createdAt: "2026-05-25",
  },
  {
    id: "cont-11",
    organizationId: "org-worqester-01",
    companyId: "comp-10",
    companyName: "Quantum FinTech Labs",
    name: "Rhea Chawla",
    designation: "Head of Risk & Payments",
    email: "rhea@quantumfin.demo",
    phone: "+91 91098 00001",
    location: "Ahmedabad",
    lastContacted: "2026-09-01",
    tags: ["Security"],
    createdAt: "2026-06-15",
  },
];

export const initialLeads: Lead[] = [
  {
    id: "lead-01",
    organizationId: "org-worqester-01",
    name: "Pooja Hegde",
    company: "Metro Rail Automated Systems",
    email: "p.hegde@metrorail-systems.demo",
    phone: "+91 98450 11223",
    industry: "Transportation & Smart City",
    source: "Inbound Website Demo",
    ownerId: "usr-03",
    ownerName: "Marcus Reed",
    status: "Qualified",
    priority: "High",
    score: 88,
    expectedValue: 3500000,
    nextFollowUp: "2026-09-06",
    createdAt: "2026-08-15",
  },
  {
    id: "lead-02",
    organizationId: "org-worqester-01",
    name: "Gaurav Malhotra",
    company: "Delta Aerospace Robotics",
    email: "g.malhotra@delta-aero.demo",
    phone: "+91 98110 33445",
    industry: "Aerospace & Defense",
    source: "Industry Expo",
    ownerId: "usr-03",
    ownerName: "Marcus Reed",
    status: "Contacted",
    priority: "Critical",
    score: 92,
    expectedValue: 7200000,
    nextFollowUp: "2026-09-05",
    createdAt: "2026-08-20",
  },
  {
    id: "lead-03",
    organizationId: "org-worqester-01",
    name: "Shreya Joshi",
    company: "FinServ Microcredits",
    email: "shreya.j@finserv-micro.demo",
    phone: "+91 97660 55667",
    industry: "Microfinance",
    source: "Referral",
    ownerId: "usr-03",
    ownerName: "Marcus Reed",
    status: "New",
    priority: "Medium",
    score: 64,
    expectedValue: 1800000,
    nextFollowUp: "2026-09-07",
    createdAt: "2026-08-29",
  },
  {
    id: "lead-04",
    organizationId: "org-worqester-01",
    name: "Naveen Reddy",
    company: "GreenVolt EV Infrastructure",
    email: "n.reddy@greenvolt-ev.demo",
    phone: "+91 96550 77889",
    industry: "Clean Energy",
    source: "LinkedIn Outreach",
    ownerId: "usr-03",
    ownerName: "Marcus Reed",
    status: "Qualified",
    priority: "High",
    score: 82,
    expectedValue: 4200000,
    nextFollowUp: "2026-09-09",
    createdAt: "2026-08-18",
  },
  {
    id: "lead-05",
    organizationId: "org-worqester-01",
    name: "Deepika Verma",
    company: "Cognitive Edutech Global",
    email: "deepika@cognitive-edutech.demo",
    phone: "+91 95440 99001",
    industry: "Education Technology",
    source: "Webinar Attendee",
    ownerId: "usr-03",
    ownerName: "Marcus Reed",
    status: "Converted",
    priority: "Medium",
    score: 79,
    expectedValue: 2400000,
    nextFollowUp: "2026-08-28",
    createdAt: "2026-08-01",
  },
  {
    id: "lead-06",
    organizationId: "org-worqester-01",
    name: "Alok Nanda",
    company: "Apex Retailers Network",
    email: "alok@apexretail.demo",
    phone: "+91 94330 12345",
    industry: "Retail",
    source: "Outbound Call",
    ownerId: "usr-03",
    ownerName: "Marcus Reed",
    status: "Lost",
    priority: "Low",
    score: 45,
    expectedValue: 1200000,
    nextFollowUp: "2026-08-10",
    createdAt: "2026-07-22",
  },
  {
    id: "lead-07",
    organizationId: "org-worqester-01",
    name: "Kavita Nair",
    company: "BioCare Diagnostics",
    email: "kavita.n@biocare-diag.demo",
    phone: "+91 93220 54321",
    industry: "Healthcare Diagnostics",
    source: "Partner Channel",
    ownerId: "usr-03",
    ownerName: "Marcus Reed",
    status: "Contacted",
    priority: "High",
    score: 85,
    expectedValue: 3900000,
    nextFollowUp: "2026-09-08",
    createdAt: "2026-08-25",
  },
  {
    id: "lead-08",
    organizationId: "org-worqester-01",
    name: "Rohan Kapoor",
    company: "SmartGrid Automation Ltd",
    email: "rohan.k@smartgrid.demo",
    phone: "+91 92110 98765",
    industry: "Utilities",
    source: "Inbound Website Demo",
    ownerId: "usr-03",
    ownerName: "Marcus Reed",
    status: "New",
    priority: "Critical",
    score: 91,
    expectedValue: 6100000,
    nextFollowUp: "2026-09-05",
    createdAt: "2026-09-01",
  },
];

export const initialDeals: Deal[] = [
  {
    id: "deal-01",
    organizationId: "org-worqester-01",
    name: "Acme Global Cloud Portal Migration",
    companyId: "comp-01",
    companyName: "Acme Technologies",
    contactId: "cont-01",
    contactName: "Rajesh Kulkarni",
    ownerId: "usr-03",
    ownerName: "Marcus Reed",
    stage: "Negotiation",
    amount: 5400000,
    probability: 85,
    expectedCloseDate: "2026-09-18",
    priority: "Critical",
    source: "Existing Client Expansion",
    createdAt: "2026-07-15",
    updatedAt: "2026-08-30",
  },
  {
    id: "deal-02",
    organizationId: "org-worqester-01",
    name: "Nova Systems Enterprise Fleet Deal",
    companyId: "comp-02",
    companyName: "Nova Systems",
    contactId: "cont-03",
    contactName: "Siddharth Sen",
    ownerId: "usr-03",
    ownerName: "Marcus Reed",
    stage: "Proposal",
    amount: 3800000,
    probability: 60,
    expectedCloseDate: "2026-09-28",
    priority: "High",
    source: "Inbound RFP",
    createdAt: "2026-07-28",
    updatedAt: "2026-08-25",
  },
  {
    id: "deal-03",
    organizationId: "org-worqester-01",
    name: "Vertex IoT Fleet Management License",
    companyId: "comp-03",
    companyName: "Vertex Solutions",
    contactId: "cont-04",
    contactName: "Meera Krishnan",
    ownerId: "usr-03",
    ownerName: "Marcus Reed",
    stage: "Discovery",
    amount: 2900000,
    probability: 45,
    expectedCloseDate: "2026-10-15",
    priority: "Medium",
    source: "Partner Network",
    createdAt: "2026-08-10",
    updatedAt: "2026-08-29",
  },
  {
    id: "deal-04",
    organizationId: "org-worqester-01",
    name: "BlueWave Logistics Microservices Modernization",
    companyId: "comp-04",
    companyName: "BlueWave Digital",
    contactId: "cont-05",
    contactName: "Karan Johar-Roy",
    ownerId: "usr-03",
    ownerName: "Marcus Reed",
    stage: "Closed Won",
    amount: 6800000,
    probability: 100,
    expectedCloseDate: "2026-08-20",
    priority: "Critical",
    source: "Direct Sales",
    createdAt: "2026-06-05",
    updatedAt: "2026-08-20",
  },
  {
    id: "deal-05",
    organizationId: "org-worqester-01",
    name: "Orion Health HIPAA Data Pipeline",
    companyId: "comp-05",
    companyName: "Orion Enterprises",
    contactId: "cont-06",
    contactName: "Dr. Lakshmi Narayanan",
    ownerId: "usr-01",
    ownerName: "Alex Vance",
    stage: "Qualification",
    amount: 4500000,
    probability: 35,
    expectedCloseDate: "2026-10-30",
    priority: "High",
    source: "Executive Inbound",
    createdAt: "2026-08-12",
    updatedAt: "2026-08-26",
  },
  {
    id: "deal-06",
    organizationId: "org-worqester-01",
    name: "Zenith Core 5G Analytics Engine",
    companyId: "comp-06",
    companyName: "Zenith Global Telecom",
    contactId: "cont-07",
    contactName: "Arjun Singhal",
    ownerId: "usr-03",
    ownerName: "Marcus Reed",
    stage: "Closed Won",
    amount: 11200000,
    probability: 100,
    expectedCloseDate: "2026-07-31",
    priority: "Critical",
    source: "Enterprise Master Agreement",
    createdAt: "2026-05-10",
    updatedAt: "2026-07-31",
  },
  {
    id: "deal-07",
    organizationId: "org-worqester-01",
    name: "Quantum FinTech Real-Time Fraud Shield",
    companyId: "comp-10",
    companyName: "Quantum FinTech Labs",
    contactId: "cont-11",
    contactName: "Rhea Chawla",
    ownerId: "usr-03",
    ownerName: "Marcus Reed",
    stage: "Proposal",
    amount: 3200000,
    probability: 70,
    expectedCloseDate: "2026-09-25",
    priority: "High",
    source: "FinTech Expo Demo",
    createdAt: "2026-08-05",
    updatedAt: "2026-09-01",
  },
  {
    id: "deal-08",
    organizationId: "org-worqester-01",
    name: "Apex Logistics Warehouse Tracking POC",
    companyId: "comp-07",
    companyName: "Apex Logistics Hub",
    contactId: "cont-08",
    contactName: "Vikas Aggarwal",
    ownerId: "usr-03",
    ownerName: "Marcus Reed",
    stage: "Closed Lost",
    amount: 1400000,
    probability: 0,
    expectedCloseDate: "2026-08-12",
    priority: "Low",
    source: "Cold Outreach",
    createdAt: "2026-06-12",
    updatedAt: "2026-08-15",
  },
];

export const initialProjects: Project[] = [
  {
    id: "proj-01",
    organizationId: "org-worqester-01",
    name: "Cloud Infrastructure Modernization",
    code: "CIM-2026",
    companyId: "comp-01",
    companyName: "Acme Technologies",
    projectManagerId: "usr-04",
    projectManagerName: "Elena Rostova",
    teamMemberIds: ["usr-04", "usr-05"],
    startDate: "2026-05-01",
    endDate: "2026-10-31",
    priority: "Critical",
    status: "In Progress",
    health: "At Risk",
    budget: 6500000,
    spent: 4200000,
    progress: 68,
    description: "Kubernetes orchestration upgrade, multi-region database failover, and zero-trust IAM gateway implementation.",
    createdAt: "2026-05-01",
  },
  {
    id: "proj-02",
    organizationId: "org-worqester-01",
    name: "AI Customer Intelligence Portal",
    code: "ACP-2026",
    companyId: "comp-04",
    companyName: "BlueWave Digital",
    projectManagerId: "usr-04",
    projectManagerName: "Elena Rostova",
    teamMemberIds: ["usr-04", "usr-05"],
    startDate: "2026-06-15",
    endDate: "2026-11-30",
    priority: "High",
    status: "In Progress",
    health: "Healthy",
    budget: 4800000,
    spent: 2400000,
    progress: 54,
    description: "Predictive churn models, conversational customer AI agent, and automated ticketing pipeline.",
    createdAt: "2026-06-15",
  },
  {
    id: "proj-03",
    organizationId: "org-worqester-01",
    name: "Enterprise Cybersecurity Assessment & Zero Trust",
    code: "ECA-2026",
    companyId: "comp-02",
    companyName: "Nova Systems",
    projectManagerId: "usr-04",
    projectManagerName: "Elena Rostova",
    teamMemberIds: ["usr-04", "usr-05"],
    startDate: "2026-07-01",
    endDate: "2026-09-30",
    priority: "Critical",
    status: "In Progress",
    health: "Watch",
    budget: 3200000,
    spent: 2100000,
    progress: 75,
    description: "SOC2 Type II remediation, API token rotating policy, and pen-testing audit suite.",
    createdAt: "2026-07-01",
  },
  {
    id: "proj-04",
    organizationId: "org-worqester-01",
    name: "Mobile Workforce Operations App",
    code: "MWO-2026",
    companyId: "comp-04",
    companyName: "BlueWave Digital",
    projectManagerId: "usr-04",
    projectManagerName: "Elena Rostova",
    teamMemberIds: ["usr-05"],
    startDate: "2026-04-10",
    endDate: "2026-08-30",
    priority: "Medium",
    status: "Completed",
    health: "Healthy",
    budget: 2500000,
    spent: 2420000,
    progress: 100,
    description: "Cross-platform mobile client for warehouse barcode scanning and shipment dispatching.",
    createdAt: "2026-04-10",
  },
  {
    id: "proj-05",
    organizationId: "org-worqester-01",
    name: "Decentralized Settlement Gateway",
    code: "DSG-2026",
    companyId: "comp-10",
    companyName: "Quantum FinTech Labs",
    projectManagerId: "usr-04",
    projectManagerName: "Elena Rostova",
    teamMemberIds: ["usr-04", "usr-05"],
    startDate: "2026-08-01",
    endDate: "2027-01-31",
    priority: "High",
    status: "Planning",
    health: "Healthy",
    budget: 5200000,
    spent: 450000,
    progress: 15,
    description: "High-throughput payment validation protocol handling 10,000 TPS under RBI regulatory sandbox.",
    createdAt: "2026-08-01",
  },
];

export const initialTasks: Task[] = [
  {
    id: "task-101",
    organizationId: "org-worqester-01",
    title: "Auth Token Rotation & Session Migration",
    description: "Migrate legacy JWT refresh tokens to secure ephemeral session cookies to satisfy SOC2 compliance requirement.",
    projectId: "proj-01",
    projectName: "Cloud Infrastructure Modernization",
    epic: "Security Hardening",
    assigneeId: "usr-05",
    assigneeName: "Vikram Patel",
    assigneeAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    reporterId: "usr-04",
    reporterName: "Elena Rostova",
    priority: "Critical",
    status: "Blocked",
    labels: ["Security", "Backend", "SLA-Breached"],
    dueDate: "2026-09-02",
    estimatedHours: 24,
    actualHours: 28,
    slaBreached: true,
    notes: "Requires coordination with Security Ops to verify session invalidation tests across distributed nodes.",
    comments: [
      {
        id: "cm-01",
        taskId: "task-101",
        authorId: "usr-04",
        authorName: "Elena Rostova",
        authorAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
        content: "Please ensure this satisfies the ISO-27001 audit controls before Thursday's compliance sync.",
        createdAt: "2026-09-01T10:30:00Z"
      },
      {
        id: "cm-02",
        taskId: "task-101",
        authorId: "usr-05",
        authorName: "Vikram Patel",
        authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
        content: "Implemented token revocation blocklist in Redis. Running cluster validation tests today.",
        createdAt: "2026-09-02T14:15:00Z"
      }
    ],
    createdAt: "2026-08-20",
  },
  {
    id: "task-102",
    organizationId: "org-worqester-01",
    title: "Database Read-Replica Auto-Scaling",
    description: "Configure read-replica scaling thresholds in Mumbai GCP region to handle peak load spikes.",
    projectId: "proj-01",
    projectName: "Cloud Infrastructure Modernization",
    epic: "Infrastructure",
    assigneeId: "usr-05",
    assigneeName: "Vikram Patel",
    assigneeAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    reporterId: "usr-04",
    reporterName: "Elena Rostova",
    priority: "High",
    status: "In Progress",
    labels: ["Cloud", "DevOps"],
    dueDate: "2026-09-07",
    estimatedHours: 16,
    actualHours: 10,
    notes: "Auto-scaler minimum pool set to 2 replicas, peak burst capacity set to 6 replicas.",
    comments: [
      {
        id: "cm-03",
        taskId: "task-102",
        authorId: "usr-05",
        authorName: "Vikram Patel",
        authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
        content: "Replica scale-out latency reduced to under 90 seconds in preliminary staging benchmarks.",
        createdAt: "2026-09-05T11:00:00Z"
      }
    ],
    createdAt: "2026-08-26",
  },
  {
    id: "task-103",
    organizationId: "org-worqester-01",
    title: "Customer Churn Prediction Feature Store",
    description: "Implement BigQuery ML embeddings and pipeline to ingest customer behavioral logs.",
    projectId: "proj-02",
    projectName: "AI Customer Intelligence Portal",
    epic: "Data Pipeline",
    assigneeId: "usr-05",
    assigneeName: "Vikram Patel",
    assigneeAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    reporterId: "usr-04",
    reporterName: "Elena Rostova",
    priority: "High",
    status: "Review",
    labels: ["AI/ML", "Analytics"],
    dueDate: "2026-09-06",
    estimatedHours: 32,
    actualHours: 30,
    createdAt: "2026-08-18",
  },
  {
    id: "task-104",
    organizationId: "org-worqester-01",
    title: "SOC2 Pentest Remediation for API Gateway",
    description: "Patch rate-limiting vulnerability identified during external audit on public webhook ingress.",
    projectId: "proj-03",
    projectName: "Enterprise Cybersecurity Assessment & Zero Trust",
    epic: "Compliance",
    assigneeId: "usr-05",
    assigneeName: "Vikram Patel",
    assigneeAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    reporterId: "usr-01",
    reporterName: "Alex Vance",
    priority: "Critical",
    status: "In Progress",
    labels: ["Security", "Hotfix"],
    dueDate: "2026-09-08",
    estimatedHours: 18,
    actualHours: 8,
    createdAt: "2026-08-28",
  },
  {
    id: "task-105",
    organizationId: "org-worqester-01",
    title: "Interactive Deal Forecast View",
    description: "Build visual stage waterfall and weighted pipeline probability charts for executive dashboard.",
    projectId: "proj-02",
    projectName: "AI Customer Intelligence Portal",
    epic: "UI Components",
    assigneeId: "usr-04",
    assigneeName: "Elena Rostova",
    assigneeAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    reporterId: "usr-03",
    reporterName: "Marcus Reed",
    priority: "Medium",
    status: "To Do",
    labels: ["Frontend", "Reporting"],
    dueDate: "2026-09-12",
    estimatedHours: 12,
    actualHours: 0,
    createdAt: "2026-09-01",
  },
  {
    id: "task-106",
    organizationId: "org-worqester-01",
    title: "Automated Offboarding IT Access Revocation",
    description: "Integrate webhook trigger with Cloud IAM to revoke directory tokens on employee exit approval.",
    projectId: "proj-01",
    projectName: "Cloud Infrastructure Modernization",
    epic: "Identity & Access",
    assigneeId: "usr-04",
    assigneeName: "Elena Rostova",
    assigneeAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    reporterId: "usr-02",
    reporterName: "Priya Sharma",
    priority: "High",
    status: "Backlog",
    labels: ["HR-Tech", "Automation"],
    dueDate: "2026-09-20",
    estimatedHours: 20,
    actualHours: 0,
    createdAt: "2026-08-30",
  },
  {
    id: "task-107",
    organizationId: "org-worqester-01",
    title: "Release v2.4 Mobile App Bundle to App Store",
    description: "Signed production build validation with offline barcode caching and telemetry.",
    projectId: "proj-04",
    projectName: "Mobile Workforce Operations App",
    epic: "Deployment",
    assigneeId: "usr-05",
    assigneeName: "Vikram Patel",
    assigneeAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    reporterId: "usr-04",
    reporterName: "Elena Rostova",
    priority: "High",
    status: "Done",
    labels: ["Mobile", "Release"],
    dueDate: "2026-08-28",
    estimatedHours: 14,
    actualHours: 12,
    completedAt: "2026-08-28",
    createdAt: "2026-08-15",
  },
];

export const initialDepartments: Department[] = [
  {
    id: "dept-01",
    name: "Engineering & Cloud",
    headName: "Elena Rostova",
    headEmail: "elena.rostova@worqester.internal",
    location: "Bengaluru Innovation Hub",
    budget: 34000000,
    employeeCount: 42,
    description: "Core cloud infrastructure, scalable backend APIs, frontend client systems, and DevOps.",
  },
  {
    id: "dept-02",
    name: "Sales & Strategic Partnerships",
    headName: "Marcus Reed",
    headEmail: "marcus.reed@worqester.internal",
    location: "Mumbai Financial Tower",
    budget: 22000000,
    employeeCount: 18,
    description: "Enterprise accounts, outbound expansion, solution architecture, and customer pipeline.",
  },
  {
    id: "dept-03",
    name: "Human Resources & Talent",
    headName: "Priya Sharma",
    headEmail: "priya.sharma@worqester.internal",
    location: "Bengaluru Innovation Hub",
    budget: 9500000,
    employeeCount: 8,
    description: "Talent acquisition, employee experience, compensation & benefits, and compliance.",
  },
  {
    id: "dept-04",
    name: "Product & UX Design",
    headName: "Aarav Mehta",
    headEmail: "aarav.mehta@worqester.internal",
    location: "Bengaluru Innovation Hub",
    budget: 14000000,
    employeeCount: 14,
    description: "Product roadmap, user research, interaction design, and design systems.",
  },
  {
    id: "dept-05",
    name: "Finance & Operations",
    headName: "Alex Vance",
    headEmail: "alex.vance@worqester.internal",
    location: "Bengaluru Innovation Hub",
    budget: 11000000,
    employeeCount: 6,
    description: "Financial governance, budgeting, audit, billing, and organizational operations.",
  },
];

export const initialEmployees: Employee[] = [
  {
    id: "emp-01",
    organizationId: "org-worqester-01",
    employeeNumber: "WQ-1001",
    firstName: "Alex",
    lastName: "Vance",
    fullName: "Alex Vance",
    email: "alex.vance@worqester.internal",
    phone: "+91 98450 00101",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    department: "Finance & Operations",
    team: "Executive Leadership",
    designation: "Chief Operations Officer",
    location: "Bengaluru",
    employmentType: "Full Time",
    joiningDate: "2023-01-10",
    status: "Active",
    workMode: "Hybrid",
    skills: ["Strategic Planning", "Financial Modeling", "Risk Management", "GCP Governance"],
    capacityHoursPerWeek: 40,
    loggedHoursThisWeek: 38,
    leaveBalanceDays: 18,
    salaryBasic: 320000,
    bankAccountMasked: "HDFC **** 4912",
  },
  {
    id: "emp-02",
    organizationId: "org-worqester-01",
    employeeNumber: "WQ-1002",
    firstName: "Priya",
    lastName: "Sharma",
    fullName: "Priya Sharma",
    email: "priya.sharma@worqester.internal",
    phone: "+91 98450 00102",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    department: "Human Resources & Talent",
    team: "People Ops",
    designation: "Head of People & Culture",
    location: "Bengaluru",
    employmentType: "Full Time",
    joiningDate: "2023-03-15",
    status: "Active",
    workMode: "Hybrid",
    skills: ["Talent Strategy", "Compensation & Benefits", "Employee Relations", "HR Analytics"],
    capacityHoursPerWeek: 40,
    loggedHoursThisWeek: 39,
    leaveBalanceDays: 14,
    salaryBasic: 240000,
    bankAccountMasked: "ICICI **** 9081",
  },
  {
    id: "emp-03",
    organizationId: "org-worqester-01",
    employeeNumber: "WQ-1003",
    firstName: "Marcus",
    lastName: "Reed",
    fullName: "Marcus Reed",
    email: "marcus.reed@worqester.internal",
    phone: "+91 98450 00103",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    department: "Sales & Strategic Partnerships",
    team: "Enterprise Sales",
    designation: "Director of Enterprise Sales",
    location: "Mumbai",
    employmentType: "Full Time",
    joiningDate: "2023-06-01",
    status: "Active",
    workMode: "Hybrid",
    skills: ["Enterprise Sales", "Contract Negotiation", "Key Account Management", "CRM Strategy"],
    capacityHoursPerWeek: 40,
    loggedHoursThisWeek: 42,
    leaveBalanceDays: 12,
    salaryBasic: 280000,
    bankAccountMasked: "Axis **** 3321",
  },
  {
    id: "emp-04",
    organizationId: "org-worqester-01",
    employeeNumber: "WQ-1004",
    firstName: "Elena",
    lastName: "Rostova",
    fullName: "Elena Rostova",
    email: "elena.rostova@worqester.internal",
    phone: "+91 98450 00104",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    department: "Engineering & Cloud",
    team: "Technical Program Management",
    designation: "Principal Technical Program Manager",
    location: "Bengaluru",
    employmentType: "Full Time",
    joiningDate: "2023-08-20",
    status: "Active",
    workMode: "On-site",
    skills: ["Agile/Scrum", "Cloud Delivery", "Release Engineering", "Cross-Team Coordination"],
    capacityHoursPerWeek: 40,
    loggedHoursThisWeek: 44,
    leaveBalanceDays: 16,
    salaryBasic: 260000,
    bankAccountMasked: "SBI **** 1198",
  },
  {
    id: "emp-05",
    organizationId: "org-worqester-01",
    employeeNumber: "WQ-1005",
    firstName: "Vikram",
    lastName: "Patel",
    fullName: "Vikram Patel",
    email: "vikram.patel@worqester.internal",
    phone: "+91 98450 00105",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    department: "Engineering & Cloud",
    team: "Core Platform",
    designation: "Lead Full Stack Engineer",
    managerId: "emp-04",
    managerName: "Elena Rostova",
    location: "Bengaluru",
    employmentType: "Full Time",
    joiningDate: "2023-11-10",
    status: "Active",
    workMode: "Hybrid",
    skills: ["React 19", "TypeScript", "Node.js", "Docker", "GCP", "PostgreSQL"],
    capacityHoursPerWeek: 40,
    loggedHoursThisWeek: 46,
    leaveBalanceDays: 15,
    salaryBasic: 210000,
    bankAccountMasked: "HDFC **** 7741",
  },
  {
    id: "emp-06",
    organizationId: "org-worqester-01",
    employeeNumber: "WQ-1006",
    firstName: "Sneha",
    lastName: "Iyer",
    fullName: "Sneha Iyer",
    email: "sneha.iyer@worqester.internal",
    phone: "+91 98450 00106",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    department: "Engineering & Cloud",
    team: "Data & AI",
    designation: "Senior Machine Learning Engineer",
    managerId: "emp-04",
    managerName: "Elena Rostova",
    location: "Bengaluru",
    employmentType: "Full Time",
    joiningDate: "2024-02-01",
    status: "Active",
    workMode: "Remote",
    skills: ["Python", "TensorFlow", "Gemini API", "BigQuery", "Vector Embeddings"],
    capacityHoursPerWeek: 40,
    loggedHoursThisWeek: 38,
    leaveBalanceDays: 14,
    salaryBasic: 225000,
    bankAccountMasked: "Kotak **** 5432",
  },
  {
    id: "emp-07",
    organizationId: "org-worqester-01",
    employeeNumber: "WQ-1007",
    firstName: "Anand",
    lastName: "Menon",
    fullName: "Anand Menon",
    email: "anand.menon@worqester.internal",
    phone: "+91 98450 00107",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    department: "Product & UX Design",
    team: "Design Systems",
    designation: "Senior Product Designer",
    location: "Bengaluru",
    employmentType: "Full Time",
    joiningDate: "2024-03-15",
    status: "Active",
    workMode: "Hybrid",
    skills: ["Figma", "Design Systems", "Tailwind CSS", "User Research", "Prototyping"],
    capacityHoursPerWeek: 40,
    loggedHoursThisWeek: 37,
    leaveBalanceDays: 13,
    salaryBasic: 190000,
    bankAccountMasked: "HDFC **** 8820",
  },
  {
    id: "emp-08",
    organizationId: "org-worqester-01",
    employeeNumber: "WQ-1008",
    firstName: "Kavita",
    lastName: "Sen",
    fullName: "Kavita Sen",
    email: "kavita.sen@worqester.internal",
    phone: "+91 98450 00108",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    department: "Sales & Strategic Partnerships",
    team: "Enterprise Sales",
    designation: "Enterprise Account Executive",
    managerId: "emp-03",
    managerName: "Marcus Reed",
    location: "Mumbai",
    employmentType: "Full Time",
    joiningDate: "2024-04-10",
    status: "Active",
    workMode: "On-site",
    skills: ["B2B SaaS Sales", "Discovery Calls", "RFP Management", "Pipeline Forecasting"],
    capacityHoursPerWeek: 40,
    loggedHoursThisWeek: 40,
    leaveBalanceDays: 12,
    salaryBasic: 175000,
    bankAccountMasked: "ICICI **** 6610",
  },
];

export const initialAttendance: AttendanceRecord[] = [
  {
    id: "att-01",
    employeeId: "emp-01",
    employeeName: "Alex Vance",
    date: "2026-09-04",
    checkIn: "08:45 AM",
    totalHours: 8.5,
    status: "Present",
    workMode: "Office",
  },
  {
    id: "att-02",
    employeeId: "emp-02",
    employeeName: "Priya Sharma",
    date: "2026-09-04",
    checkIn: "09:05 AM",
    totalHours: 8.0,
    status: "Present",
    workMode: "Office",
  },
  {
    id: "att-03",
    employeeId: "emp-03",
    employeeName: "Marcus Reed",
    date: "2026-09-04",
    checkIn: "09:15 AM",
    totalHours: 8.2,
    status: "Present",
    workMode: "Office",
  },
  {
    id: "att-04",
    employeeId: "emp-04",
    employeeName: "Elena Rostova",
    date: "2026-09-04",
    checkIn: "08:30 AM",
    totalHours: 9.0,
    status: "Present",
    workMode: "Office",
  },
  {
    id: "att-05",
    employeeId: "emp-05",
    employeeName: "Vikram Patel",
    date: "2026-09-04",
    checkIn: "09:10 AM",
    totalHours: 8.5,
    status: "Present",
    workMode: "WFH",
  },
  {
    id: "att-06",
    employeeId: "emp-06",
    employeeName: "Sneha Iyer",
    date: "2026-09-04",
    checkIn: "09:00 AM",
    totalHours: 8.0,
    status: "Present",
    workMode: "WFH",
  },
  {
    id: "att-07",
    employeeId: "emp-07",
    employeeName: "Anand Menon",
    date: "2026-09-04",
    checkIn: "09:30 AM",
    totalHours: 7.8,
    status: "Present",
    workMode: "Office",
  },
  {
    id: "att-08",
    employeeId: "emp-08",
    employeeName: "Kavita Sen",
    date: "2026-09-04",
    checkIn: "09:00 AM",
    totalHours: 8.0,
    status: "Present",
    workMode: "Office",
  },
];

export const initialLeaveRequests: LeaveRequest[] = [
  {
    id: "lv-01",
    employeeId: "emp-05",
    employeeName: "Vikram Patel",
    type: "Annual",
    startDate: "2026-09-15",
    endDate: "2026-09-18",
    days: 4,
    reason: "Family travel and personal commitment.",
    approverName: "Elena Rostova",
    status: "Pending",
    createdAt: "2026-09-01",
  },
  {
    id: "lv-02",
    employeeId: "emp-08",
    employeeName: "Kavita Sen",
    type: "Casual",
    startDate: "2026-09-11",
    endDate: "2026-09-11",
    days: 1,
    reason: "Personal banking and urgent errands.",
    approverName: "Marcus Reed",
    status: "Approved",
    createdAt: "2026-08-30",
  },
  {
    id: "lv-03",
    employeeId: "emp-07",
    employeeName: "Anand Menon",
    type: "Sick",
    startDate: "2026-08-25",
    endDate: "2026-08-26",
    days: 2,
    reason: "Severe viral fever and physician prescribed rest.",
    approverName: "Priya Sharma",
    status: "Approved",
    createdAt: "2026-08-25",
  },
];

export const initialJobPositions: JobPosition[] = [
  {
    id: "job-01",
    title: "Senior Cloud Platform Engineer (Kubernetes)",
    department: "Engineering & Cloud",
    location: "Bengaluru",
    openings: 2,
    hiringManager: "Elena Rostova",
    status: "Open",
    salaryRange: "₹24L - ₹32L PA",
    experience: "5-8 Years",
  },
  {
    id: "job-02",
    title: "Enterprise Solutions Architect (BFSI)",
    department: "Sales & Strategic Partnerships",
    location: "Mumbai",
    openings: 1,
    hiringManager: "Marcus Reed",
    status: "Open",
    salaryRange: "₹28L - ₹38L PA",
    experience: "7-10 Years",
  },
  {
    id: "job-03",
    title: "Talent Acquisition Specialist",
    department: "Human Resources & Talent",
    location: "Bengaluru",
    openings: 1,
    hiringManager: "Priya Sharma",
    status: "Open",
    salaryRange: "₹12L - ₹16L PA",
    experience: "3-5 Years",
  },
];

export const initialCandidates: Candidate[] = [
  {
    id: "cand-01",
    name: "Aditya Verma",
    email: "aditya.verma.tech@gmail.demo",
    phone: "+91 98112 88776",
    positionId: "job-01",
    positionTitle: "Senior Cloud Platform Engineer (Kubernetes)",
    stage: "Technical",
    experienceYears: 6.5,
    rating: 4.8,
    appliedDate: "2026-08-22",
  },
  {
    id: "cand-02",
    name: "Rituja Salunke",
    email: "rituja.salunke@outlook.demo",
    phone: "+91 98223 44556",
    positionId: "job-02",
    positionTitle: "Enterprise Solutions Architect (BFSI)",
    stage: "Managerial",
    experienceYears: 8.0,
    rating: 4.5,
    appliedDate: "2026-08-19",
  },
  {
    id: "cand-03",
    name: "Karthik Nair",
    email: "karthik.nair91@gmail.demo",
    phone: "+91 97441 22334",
    positionId: "job-01",
    positionTitle: "Senior Cloud Platform Engineer (Kubernetes)",
    stage: "Offer",
    experienceYears: 7.0,
    rating: 4.9,
    appliedDate: "2026-08-10",
  },
  {
    id: "cand-04",
    name: "Divya Kapoor",
    email: "divya.kapoor@talent.demo",
    phone: "+91 96552 11009",
    positionId: "job-03",
    positionTitle: "Talent Acquisition Specialist",
    stage: "Interview",
    experienceYears: 4.0,
    rating: 4.2,
    appliedDate: "2026-08-27",
  },
];

export const initialExpenses: Expense[] = [
  {
    id: "exp-01",
    employeeId: "emp-03",
    employeeName: "Marcus Reed",
    category: "Client Meeting",
    amount: 14500,
    date: "2026-08-29",
    description: "Executive dinner with CTO of Acme Technologies to negotiate expansion contract.",
    projectName: "Cloud Infrastructure Modernization",
    status: "Approved",
  },
  {
    id: "exp-02",
    employeeId: "emp-05",
    employeeName: "Vikram Patel",
    category: "Software",
    amount: 8200,
    date: "2026-08-24",
    description: "Annual subscription for cloud security profiling diagnostic tooling.",
    projectName: "Enterprise Cybersecurity Assessment & Zero Trust",
    status: "Approved",
  },
  {
    id: "exp-03",
    employeeId: "emp-04",
    employeeName: "Elena Rostova",
    category: "Travel",
    amount: 22400,
    date: "2026-08-18",
    description: "Flight and cab transit for onsite quarterly architecture review in Mumbai.",
    projectName: "Cloud Infrastructure Modernization",
    status: "Approved",
  },
  {
    id: "exp-04",
    employeeId: "emp-05",
    employeeName: "Vikram Patel",
    category: "Office",
    amount: 5400,
    date: "2026-09-02",
    description: "Ergonomic keyboard and USB-C multiport adapter reimbursement claim.",
    projectName: "Cloud Infrastructure Modernization",
    status: "Pending",
  },
];

export const initialAssets: Asset[] = [
  {
    id: "ast-01",
    name: "MacBook Pro M3 Max 16-inch",
    category: "Laptop",
    serialNumber: "C02G998XYZ01",
    employeeName: "Vikram Patel",
    employeeId: "emp-05",
    condition: "New",
    status: "Assigned",
  },
  {
    id: "ast-02",
    name: "Dell UltraSharp 32-inch 4K Monitor",
    category: "Monitor",
    serialNumber: "DL-U3223-9941",
    employeeName: "Vikram Patel",
    employeeId: "emp-05",
    condition: "Good",
    status: "Assigned",
  },
  {
    id: "ast-03",
    name: "MacBook Pro M3 Pro 14-inch",
    category: "Laptop",
    serialNumber: "C02G887XYZ02",
    employeeName: "Sneha Iyer",
    employeeId: "emp-06",
    condition: "New",
    status: "Assigned",
  },
  {
    id: "ast-04",
    name: "Lenovo ThinkPad X1 Carbon Gen 11",
    category: "Laptop",
    serialNumber: "TP-X1-2024-551",
    employeeName: "Priya Sharma",
    employeeId: "emp-02",
    condition: "Good",
    status: "Assigned",
  },
];

export const initialDocuments: DocumentItem[] = [
  {
    id: "doc-01",
    title: "Acme Technologies Master Services Agreement 2026",
    name: "Acme_Technologies_Master_Services_Agreement_2026.pdf",
    fileName: "Acme_Technologies_Master_Services_Agreement_2026.pdf",
    category: "Contracts",
    size: "3.4 MB",
    fileSize: "3.4 MB",
    fileType: "pdf",
    version: "v1.2",
    uploadedBy: "Marcus Reed",
    uploadedAt: "2026-07-20",
    expiryDate: "2027-07-19",
    tags: ["MSA", "Signed", "Acme"],
  },
  {
    id: "doc-02",
    title: "SOC2 Type II Compliance Security Architecture",
    name: "SOC2_Type_II_Compliance_Security_Architecture.pdf",
    fileName: "SOC2_Type_II_Compliance_Security_Architecture.pdf",
    category: "Policies",
    size: "5.8 MB",
    fileSize: "5.8 MB",
    fileType: "pdf",
    version: "v2.0",
    uploadedBy: "Alex Vance",
    uploadedAt: "2026-08-10",
    expiryDate: "2027-08-09",
    tags: ["Compliance", "Audit", "GCP"],
  },
  {
    id: "doc-03",
    title: "Worqester Employee Code of Conduct v3",
    name: "Worqester_Employee_Code_of_Conduct_v3.pdf",
    fileName: "Worqester_Employee_Code_of_Conduct_v3.pdf",
    category: "Policies",
    size: "1.2 MB",
    fileSize: "1.2 MB",
    fileType: "pdf",
    version: "v3.0",
    uploadedBy: "Priya Sharma",
    uploadedAt: "2026-01-05",
    tags: ["HR", "Internal"],
  },
  {
    id: "doc-04",
    title: "BlueWave Logistics SOW Phase 2 Microservices",
    name: "BlueWave_Logistics_SOW_Phase2_Microservices.pdf",
    fileName: "BlueWave_Logistics_SOW_Phase2_Microservices.pdf",
    category: "Proposals",
    size: "2.7 MB",
    fileSize: "2.7 MB",
    fileType: "pdf",
    version: "v1.0",
    uploadedBy: "Elena Rostova",
    uploadedAt: "2026-08-25",
    tags: ["SOW", "Signed"],
  },
];

export const initialNotes: NoteItem[] = [
  {
    id: "note-01",
    title: "Acme Cloud Architecture Review Notes",
    content: "Key stakeholder Rajesh Kulkarni noted that auto-scaling in the Mumbai region must handle unexpected 4x traffic on Diwali weekend. Follow up with updated architecture diagram.",
    tags: ["Acme", "Architecture", "Priority"],
    pinned: true,
    linkedEntity: "comp-01",
    updatedAt: "2026-08-29",
  },
  {
    id: "note-02",
    title: "Q4 Engineering Hiring Priorities",
    content: "Plan to open 2 additional Senior Go/Rust distributed systems roles once Series B allocation sync concludes with Finance.",
    tags: ["HR", "Recruitment", "Headcount"],
    pinned: false,
    linkedEntity: "dept-01",
    updatedAt: "2026-08-25",
  },
  {
    id: "note-03",
    title: "Customer 360 Health Alert: Vertex Solutions",
    content: "Client has been in leadership transition. Coordinate with Marcus for an executive dinner in Delhi next week.",
    tags: ["Customer 360", "Watchlist"],
    pinned: true,
    linkedEntity: "comp-03",
    updatedAt: "2026-08-31",
  },
];

export const initialActivities: ActivityItem[] = [
  {
    id: "act-01",
    type: "Meeting",
    title: "Quarterly Executive Steering Committee with Acme",
    description: "Presented migration milestones, reviewed billing run-rate, and proposed expansion to Gemini-powered automated triage.",
    entityType: "Customer",
    entityName: "Acme Technologies",
    userName: "Marcus Reed",
    timestamp: "2026-08-30 04:30 PM",
  },
  {
    id: "act-02",
    type: "Status Change",
    title: "Project Health Alert",
    description: "Cloud Infrastructure Modernization flagged as 'At Risk' due to SLA breach on Auth Token Migration task.",
    entityType: "Project",
    entityName: "Cloud Infrastructure Modernization",
    userName: "Elena Rostova",
    timestamp: "2026-09-02 11:00 AM",
  },
  {
    id: "act-03",
    type: "Call",
    title: "Enterprise Deal Review with Nova Systems",
    description: "Discussed security SLA requirements; requested revised quote with 24/7 dedicated SRE support.",
    entityType: "Deal",
    entityName: "Nova Systems Enterprise Fleet Deal",
    userName: "Marcus Reed",
    timestamp: "2026-09-01 02:15 PM",
  },
  {
    id: "act-04",
    type: "Task",
    title: "Task Assigned",
    description: "Assigned SOC2 Pentest Remediation to Vikram Patel with due date Sep 08.",
    entityType: "Task",
    entityName: "SOC2 Pentest Remediation for API Gateway",
    userName: "Elena Rostova",
    timestamp: "2026-08-28 10:45 AM",
  },
];

export const initialAuditLogs: AuditLogItem[] = [
  {
    id: "aud-01",
    userName: "Alex Vance",
    userRole: "Admin",
    action: "Updated Settings",
    entityType: "SystemSettings",
    entityName: "Organization Branding",
    details: "Configured primary platform branding, default INR currency, and IST timezone.",
    timestamp: "2026-09-01 09:12:00",
  },
  {
    id: "aud-02",
    userName: "Marcus Reed",
    userRole: "Sales Manager",
    action: "Updated Deal Stage",
    entityType: "Deal",
    entityName: "BlueWave Logistics Microservices Modernization",
    details: "Advanced deal from Negotiation to Closed Won (Value: ₹68,00,000).",
    timestamp: "2026-08-20 16:45:10",
  },
  {
    id: "aud-03",
    userName: "Elena Rostova",
    userRole: "Project Manager",
    action: "Updated Task Status",
    entityType: "Task",
    entityName: "Auth Token Rotation & Session Migration",
    details: "Changed status from In Progress to Blocked with note: pending IAM dependency.",
    timestamp: "2026-09-02 10:30:22",
  },
  {
    id: "aud-04",
    userName: "Priya Sharma",
    userRole: "HR Manager",
    action: "Approved Leave Request",
    entityType: "LeaveRequest",
    entityName: "Kavita Sen Casual Leave",
    details: "Approved 1 day casual leave for Sep 11, 2026.",
    timestamp: "2026-08-30 14:15:00",
  },
];

export const initialAutomations: AutomationRule[] = [
  {
    id: "auto-01",
    name: "Deal Won -> Auto-Create Project",
    trigger: "WHEN Deal stage changes to 'Closed Won'",
    condition: "IF Deal Amount > ₹20,00,000",
    action: "THEN Create Project shell, assign PM, and notify Engineering Lead",
    enabled: true,
  },
  {
    id: "auto-02",
    name: "Overdue Task -> Escalation Alert",
    trigger: "WHEN Task becomes Overdue / SLA Breached",
    condition: "IF Priority is Critical or High",
    action: "THEN Notify Assignee and Project Manager, flag Project Health to At Risk",
    enabled: true,
  },
  {
    id: "auto-03",
    name: "Candidate Joined -> Trigger Onboarding Checklist",
    trigger: "WHEN Candidate stage moves to 'Joined'",
    condition: "IF Employment Type is Full Time",
    action: "THEN Generate Employee record, request Laptop Asset, and trigger HR Orientation",
    enabled: true,
  },
  {
    id: "auto-04",
    name: "Document Expiry 30-Day Warning",
    trigger: "WHEN Document expiry is within 30 days",
    condition: "IF Category is 'Contracts' or 'Policies'",
    action: "THEN Create Notification for Legal and Account Owner",
    enabled: true,
  },
];

export const initialMilestones: Milestone[] = [
  {
    id: "mls-01",
    projectId: "proj-01",
    projectName: "Cloud Infrastructure Modernization",
    name: "V1 Cloud Ingestion Architecture & Kafka Pipeline",
    dueDate: "2026-09-30",
    status: "In Progress",
    weight: "25% Payment Milestone",
    description: "Cloud data pipeline verification and throughput load test",
  },
  {
    id: "mls-02",
    projectId: "proj-02",
    projectName: "Enterprise Cybersecurity Assessment & Zero Trust",
    name: "SOC2 Type II Audit Compliance Report Acceptance",
    dueDate: "2026-10-15",
    status: "Pending Review",
    weight: "Final Sign-off",
    description: "Independent security auditor sign-off and risk remediation",
  },
  {
    id: "mls-03",
    projectId: "proj-03",
    projectName: "NextGen ERP Engine",
    name: "Core Platform Modernization Alpha Release",
    dueDate: "2026-11-20",
    status: "Planning",
    weight: "40% Deliverable",
    description: "Alpha build containerization and client staging release",
  },
];

export const initialInvitations: UserInvitation[] = [
  {
    id: "inv-01",
    name: "Siddharth Mehra",
    email: "siddharth.m@partner.worqester.internal",
    role: "Project Manager",
    department: "Engineering",
    status: "Pending",
    invitedAt: "2026-09-15",
  },
  {
    id: "inv-02",
    name: "Ananya Roy",
    email: "ananya.roy@worqester.internal",
    role: "Sales Executive",
    department: "Sales & Revenue",
    status: "Pending",
    invitedAt: "2026-09-16",
  },
];
